version: '3'
services:
    web:
        build: .
        volumes:
            - .:/metrikgile/
        ports:
            - "8000:8000"
        command: python3 manage.py runserver 0.0.0.0:8000

    db:
        image: postgres
        environment:
            - POSTGRES_DB=metrikgile_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
